name: pedantic
version: 1.9.0
description: >
  The Dart analyzer settings and best practices used internally at Google.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pedantic

environment:
  sdk: '>=2.1.1-dev.0.0 <3.0.0'
